// Code generated by "stringer -type=DIRECTION"; DO NOT EDIT.

package dir

import "strconv"

const (
	_DIRECTION_name_0 = "NORTH"
	_DIRECTION_name_1 = "WESTNORTH_WEST"
	_DIRECTION_name_2 = "SOUTH"
	_DIRECTION_name_3 = "SOUTH_WEST"
	_DIRECTION_name_4 = "EASTNORTH_EAST"
	_DIRECTION_name_5 = "SOUTH_EAST"
	_DIRECTION_name_6 = "ANY"
	_DIRECTION_name_7 = "STOP"
)

var (
	_DIRECTION_index_1 = [...]uint8{0, 4, 14}
	_DIRECTION_index_4 = [...]uint8{0, 4, 14}
)

func (i DIRECTION) String() string {
	switch {
	case i == 1:
		return _DIRECTION_name_0
	case 4 <= i && i <= 5:
		i -= 4
		return _DIRECTION_name_1[_DIRECTION_index_1[i]:_DIRECTION_index_1[i+1]]
	case i == 8:
		return _DIRECTION_name_2
	case i == 12:
		return _DIRECTION_name_3
	case 16 <= i && i <= 17:
		i -= 16
		return _DIRECTION_name_4[_DIRECTION_index_4[i]:_DIRECTION_index_4[i+1]]
	case i == 24:
		return _DIRECTION_name_5
	case i == 29:
		return _DIRECTION_name_6
	case i == 256:
		return _DIRECTION_name_7
	default:
		return "DIRECTION(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
