// Code generated by "stringer -type=DIRECTION"; DO NOT EDIT.

package dir

import "strconv"

const _DIRECTION_name = "NORTH"

var _DIRECTION_index = [...]uint8{0, 5}

func (i DIRECTION) String() string {
	i -= 1
	if i < 0 || i >= DIRECTION(len(_DIRECTION_index)-1) {
		return "DIRECTION(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DIRECTION_name[_DIRECTION_index[i]:_DIRECTION_index[i+1]]
}
